openapi: "3.0.1"
info:
  version: 1.0.0
  title: JAVA-SPRING-PG-DOCKER
paths:
  /v1/matters:
    post:
      summary: Receiving matters
      operationId: receiveMatter
      requestBody:
        description: Matter Post object to be received
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MatterRequest"
      responses:
        '201':
          description: Service has started
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MatterResponse"
  /v1/execinterrup:
      post:
        summary: Receiving execution interrupts
        operationId: receiveExecInterrup
        requestBody:
          description: Execution Interruption Post object to be received
          required: true
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExecInterrupRequest"
        responses:
          '201':
            description: Excecution Interruption received and saved
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/ExecInterrupResponse"

components:
  schemas:
    MatterRequest:
      type: object
      required:
        - customerNr
        - matterNr
      properties:
        customerNr:
          type: integer
          format: int64
        matterNr:
          type: string
    MatterResponse:
      type: object
      required:
        - customerNr
        - chargeID
      properties:
        customerNr:
          type: integer
          format: int64
        chargeID:
          type: string
          format: uuid

    ExecInterrupRequest:
      type: object
      required:
        - customerNr
        - execInterrupType
        - matterNr
      properties:
        customerNr:
          type: integer
          format: int64
        execInterrupType:
          $ref: "#/components/schemas/ExecInterrupEnum"
        matterNr:
          type: string
    ExecInterrupResponse:
      type: object
      required:
        - customerNr
        - chargeID
      properties:
        customerNr:
          type: integer
          format: int64
        chargeID:
          type: string
          format: uuid

    VehicleTypeEnum:
      type: string
      enum:
        - bulldozer
        - dirtbike
        - unimog
    ExecInterrupEnum:
      type: string
      enum:
        - customer_deceased
        - rejected
        - withdrawn
        - paid



