openapi: "3.0.1"
info:
  version: 1.0.0
  title: JAVA-SPRING-PG-DOCKER
paths:
  /v1/cases:
    post:
      summary: Receiving cases
      operationId: receiveCase
      requestBody:
        description: Case Post object to be received
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CaseRequest"
      responses:
        '201':
          description: Service has started
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CaseResponse"

components:
  schemas:
    CaseRequest:
      type: object
      required:
        - customerNr
        - caseID
      properties:
        customerNr:
          type: integer
          format: int64
        caseID:
          type: string
    CaseResponse:
      type: object
      required:
        - customerNr
        - chargeID
        - chargeStatus
        - vehicleType
        - startDate
      properties:
        customerNr:
          type: integer
          format: int64
        chargeID:
          type: string
        chargeStatus:
          $ref: "#/components/schemas/ChargeStatusEnum"
        startDate:
          type: string
          format: date
        vehicleType:
          $ref: "#/components/schemas/VehicleTypeEnum"
        cases:
          type: array
          items:
            type: string

    ChargeStatusEnum:
      type: string
      enum:
        - booked
        - rejected
        - released
        - applied
        - treated
    VehicleTypeEnum:
      type: string
      enum:
        - bulldozer
        - dirtbike
        - unimog


