openapi: "3.0.1"
info:
  version: 1.0.0
  title: JAVA-SPRING-PG-DOCKER
paths:
  /v1/matters:
    post:
      summary: Receiving matters
      operationId: receiveMatter
      requestBody:
        description: Matter Post object to be received
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MatterRequest"
      responses:
        '201':
          description: Service has started
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MatterResponse"

components:
  schemas:
    MatterRequest:
      type: object
      required:
        - customerNr
        - matterID
      properties:
        customerNr:
          type: integer
          format: int64
        matterID:
          type: string
    MatterResponse:
      type: object
      required:
        - customerNr
        - chargeID
      properties:
        customerNr:
          type: integer
          format: int64
        chargeID:
          type: string
          format: uuid

    ChargeStatusEnum:
      type: string
      enum:
        - booked
        - rejected
        - released
        - applied
        - treated
    VehicleTypeEnum:
      type: string
      enum:
        - bulldozer
        - dirtbike
        - unimog


